// Runner-specific debug launches. Overcli exposes a standard attach endpoint;
// breakpoints, stacks and variables stay in the developer's editor.

import fs from 'node:fs';
import path from 'node:path';

import type { DebugKind, RunnerKind, ServiceSpec } from './types';

export interface DebugLaunch {
  command: string[];
  env: Record<string, string>;
  kind?: DebugKind;
  port?: number;
}

export function debugKindFor(spec: Pick<ServiceSpec, 'runner' | 'debugKind'>): DebugKind | undefined {
  if (spec.debugKind) return spec.debugKind;
  if (spec.runner === 'gradle' || spec.runner === 'spring-boot') return 'jdwp';
  if (spec.runner === 'npm' || spec.runner === 'vite' || spec.runner === 'ng-serve') return 'node-inspector';
  if (spec.runner === 'python') return 'debugpy';
  if (spec.runner === 'go') return 'delve';
  return undefined;
}

export function defaultDebugPort(runner: RunnerKind, servicePort?: number): number | undefined {
  if (runner === 'gradle' || runner === 'spring-boot') return servicePort ? servicePort + 900 : 5005;
  if (runner === 'npm' || runner === 'vite' || runner === 'ng-serve') return 9229;
  if (runner === 'python') return 5678;
  if (runner === 'go') return 2345;
  return undefined;
}

export function debugLaunch(
  spec: ServiceSpec,
  command: readonly string[],
  env: Readonly<Record<string, string>>,
  port: number | undefined,
  gradleInitPath?: string,
): DebugLaunch {
  const kind = debugKindFor(spec);
  if (!spec.debugEnabled || !kind || !port) return { command: [...command], env: { ...env } };

  const endpoint = `127.0.0.1:${port}`;
  if (kind === 'jdwp') {
    const agent = `-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=${port}`;
    if (spec.runner === 'gradle') {
      if (!gradleInitPath) return { command: [...command], env: { ...env } };
      return {
        command: [...command, '-I', gradleInitPath],
        env: { ...env, OVERCLI_DEBUG_PORT: String(port) },
        kind,
        port,
      };
    }
    return {
      command: [...command, `-Dspring-boot.run.jvmArguments=${agent}`],
      env: { ...env },
      kind,
      port,
    };
  }

  if (kind === 'node-inspector') {
    const [bin, ...args] = command;
    if (/^(node|nodejs)(\.exe)?$/i.test(path.basename(bin ?? ''))) {
      return { command: [bin, `--inspect=${endpoint}`, ...args], env: { ...env }, kind, port };
    }
    // npm passes this to lifecycle scripts without enabling its own inspector.
    // pnpm accepts the same npm-compatible environment configuration.
    const npmFamily = /^(npm|npx|pnpm)(\.cmd|\.exe)?$/i.test(path.basename(bin ?? ''));
    return {
      command: [...command],
      env: npmFamily
        ? { ...env, npm_config_node_options: `--inspect=${endpoint}` }
        : { ...env, NODE_OPTIONS: `--inspect=${endpoint}` },
      kind,
      port,
    };
  }

  if (kind === 'debugpy') {
    const [bin, ...args] = command;
    const base = path.basename(bin ?? '').toLowerCase();
    if (/^python(3(\.\d+)?)?(\.exe)?$/.test(base)) {
      return {
        command: [bin, '-m', 'debugpy', '--listen', endpoint, ...args],
        env: { ...env }, kind, port,
      };
    }
    if (base === 'uvicorn' || base === 'flask' || base === 'django-admin') {
      return {
        command: ['python', '-m', 'debugpy', '--listen', endpoint, '-m', base, ...args],
        env: { ...env }, kind, port,
      };
    }
    return { command: [...command], env: { ...env } };
  }

  if (command[0] !== 'go' || command[1] !== 'run') {
    return { command: [...command], env: { ...env } };
  }
  const target = command[2] ?? '.';
  const programArgs = command.slice(3);
  return {
    command: [
      'dlv', 'debug', target,
      '--headless', `--listen=${endpoint}`, '--api-version=2',
      '--accept-multiclient', '--continue',
      ...(programArgs.length ? ['--', ...programArgs] : []),
    ],
    env: { ...env }, kind, port,
  };
}

const GRADLE_DEBUG_INIT = `// Generated by Overcli. Changes are replaced.\nallprojects {\n    afterEvaluate { project ->\n        def port = System.getenv('OVERCLI_DEBUG_PORT')\n        if (port && project.tasks.findByName('bootRun')) {\n            project.tasks.bootRun.jvmArgs \"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=\${port}\"\n            println \">>> OVERCLI DEBUG: bootRun will listen on port \${port}\"\n        }\n    }\n}\n`;

/// Materialise the tiny Gradle adapter outside every checkout, so enabling a
/// debugger never dirties the branch being inspected.
export function ensureGradleDebugInit(dataDir: string): string {
  const dir = path.join(dataDir, 'services', '_debug');
  const file = path.join(dir, 'overcli-debug.init.gradle');
  fs.mkdirSync(dir, { recursive: true });
  if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== GRADLE_DEBUG_INIT) {
    fs.writeFileSync(file, GRADLE_DEBUG_INIT, { mode: 0o600 });
  }
  return file;
}
